language: node_js
node_js:
  - '5'
before_deploy:
  - npm run build
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  skip_cleanup: true
  api_key:
    secure: >-
      AdljWNlFrh+UabSkW/AeHTDXhL3YMEXtey3XrHgiIrGP97ud4SvhYLqJv08Zap9asnifVbZCPJoEmkq2ZOZGoZSbNWmr3MiHmCVeW2KtgBeSayRRbW4fSXxTitZNESrH8oYF4vDbWvvRePEJYi3JfyuX6fLCrPoFeWO4VeyfzLB6LWRhGKRYHQNxnVKT14HDhlO9ydqOJRTureiy1FC7ViN2Nfu/y5UbIn8Sncq42QSaM/SvPxHmQxNZ2gMD06XxaveAW+ufQmLMSUpxfktopbXbx1aps/URWsMpA0MnYSkTTHBjG+E+VFsDBx168NxOYahu07meIGBno2k79IVj5AIF832axKmSkv/K7xzGzsr2Vvb1mca30DHt2IcHQKe+pBfiuDZQd33BpiSuvrWIFFPPAv32MYO4rhnmBoR9Dx6zNvm4lEunC0z7zd/F2c2LiWc4hboJzIXVZ8kp3+1IHDu++29UJAxOjqrUnhjRNn4Cnd4iagYs2tZYJ6nwaa7ykPABTfiDrFZZRSa41UCNFTv6w/8zY30K2/cObjcYSdDf25EY+MlXpNSX9uGzg5zb4t4vDtgdRMdOrJGgovpvhwI/wlLKxI1pK6Pwabt5/CrIZsj18U/QLj6Q5s6BJd73KOsoYErrevM9FmdEx8Z3U8Xim0VexYWlZ7qFvfe6cAM=
  'on':
    tags: true
    repo: octoblu/zooid-app-version-notifier
branches:
  only:
    - '/^v[0-9]/'
notifications:
  webhooks:
    - 'https://beekeeper.octoblu.com/webhooks/travis:ci'
